name = "given"
version = "6.0.1"
# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "ğŸ‘‡ Ergonomic guards aka early returns for Bool, Result, Option, and List types in Gleam!"
licences = ["MPL-2.0"]
repository = { type = "github", user = "inoas", repo = "gleam-given" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

gleam = ">= 1.13.0"

[documentation]
pages = [
  { title = "CHANGELOG", path = "changelog.html", source = "CHANGELOG.md" },
]

[dependencies]
gleam_stdlib = ">= 0.61.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.6.0 and < 2.0.0"
